In [4]:
import numpy as np

#엠디 array= numpy안에 들어있는 클래스
a1 = np.array([[1, 2, 3], [10, 20, 30]]) #2차원 배열 
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


In [7]:
a2 = np.arange(20).reshape(4,5) #2차원 배열 #갯수가 맞아떨어져야함 ex. reshape(4,4)
print(a2)
print(a2.shape)  #(20,)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [11]:
a3 = a2.flatten() #다차원 배열을 1차원으로 만들기 , 원본을 그대로 카피
a3[3] = 100
print(a3)
print(a2)

a4 = a2.ravel() #revel은 참조값을 가져옴 
a4[3] = 200
print(a4)
print(a2)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [23]:
a2 = np.arange(20).reshape(4,5) #2차원 배열 #인덱싱은 내가원하는 부분만 가져올수 있음 
print(a2)
print(a2[1])
#print(a2[1, 2])
#print(a2[:,1])
#print(a2[:, 1:4])
#print(a2[:, 1:4:2])
#print(a2[1, :])
#print(a2[1:3, :])
#print(a2[::2,:]) #:: 처음부터 끝까지 
print(a2[::, 1:4])



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[5 6 7 8 9]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [30]:
print(a2)
#print(a2.shape) #axis(축)
#print(a2.sum()) #a2 전체 합계
#print(a2.sum(axis=0))
print(a2.sum(axis=1)) #0: 열별로 , 1: 행별로


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10 35 60 85]


In [33]:
print(a2, a2.shape) 
a3 = a2.T #축변환
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [36]:
print(a2, a2.shape)  
np.moveaxis(a2, [0], [1]) #엑세스 0을 1로 바꿔라
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [46]:
a10 = np.arange(5, 20).reshape(3,5)
print(a10, a10.shape)


#shape(3,5) 의 2차원 adarray로 만들기
a11 = (a10[:, 2:4])
print(a11, a11.shape)
print(a11.sum(axis =0))
print(np.mean(a11, axis=0)) #축을 따라 평균을 내기


[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (3, 5)
[[ 7  8]
 [12 13]
 [17 18]] (3, 2)
[36 39]
[12. 13.]


In [55]:
#1차원배열붙이기
a1=  np.arange(0, 10)
a2 = np.arange(100, 110)
print(a1)
print(a2)
a3 = np.concatenate((a1, a2))
print(a3)


[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109]
[  0   1   2   3   4   5   6   7   8   9 100 101 102 103 104 105 106 107
 108 109]


In [56]:
#2차원 배열 붙이기
a1=  np.arange(0, 10).reshape(2,5)
a2 = np.arange(100, 110).reshape(2, 5)
print(a1)
print(a2)
a3 = np.concatenate((a1, a2))
print(a3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 101 102 103 104]
 [105 106 107 108 109]]


In [61]:

a1=  np.arange(0, 10).reshape(2,5)
a2 = np.arange(100, 110).reshape(2, 5)
print(a1)
print(a2)
a3 = np.concatenate((a1, a2), axis=1)
#print(a3)

a4 = np.hstack((a1, a2))  #수평으로 2개를 붙이기
#print(a4)
a5 = np.vstack((a1, a2))
print(a5)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 101 102 103 104]
 [105 106 107 108 109]]


In [67]:
print(a4)
a6 = np.hsplit(a4, 5)
print(a6)


[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[array([[0, 1],
       [5, 6]]), array([[2, 3],
       [7, 8]]), array([[  4, 100],
       [  9, 105]]), array([[101, 102],
       [106, 107]]), array([[103, 104],
       [108, 109]])]


In [70]:
#세로로 자르기 
print(a4)
a7 = a4.T 
print(a7)
np.vsplit(a7,5) #a7을 5조각내기


[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   5]
 [  1   6]
 [  2   7]
 [  3   8]
 [  4   9]
 [100 105]
 [101 106]
 [102 107]
 [103 108]
 [104 109]]


[array([[0, 5],
        [1, 6]]),
 array([[2, 7],
        [3, 8]]),
 array([[  4,   9],
        [100, 105]]),
 array([[101, 106],
        [102, 107]]),
 array([[103, 108],
        [104, 109]])]

In [78]:
a2 = np.arange(20).reshape(4,5)
print(a2)
filter1 = (a2[:, 0]%10 ==5)
print(filter1)
print(a2[filter1])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[False  True False  True]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
