In [ ]:
import requests
import numpy as np

x = requests.get("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [59]:
raw_data =[]
for line in x.text.split('\n'):
    raw_data.append(line.split(','))

for sample in raw_data:
    if len(sample)< 1:
        continue
    for i, value in enumerate(sample[:4]):
        try:
            sample[i] = float(value)
        except:
            sample[i] =0.0

In [60]:
print(raw_data[:3])

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [4.7, 3.2, 1.3, 0.2, 'Iris-setosa']]


##문자열 -> 숫자

*iris Setosa ->0

*iris Versicolour ->1

*iris Viginica ->2

In [61]:
for sample in raw_data:
    if len(sample)<2:
        continue
    if 'setosa' in sample[-1]:
        sample[-1] = 0.0
    elif 'versicolor' in sample[-1]:
        sample[-1] = 1.0
    elif 'virginica' in sample[-1]:
        sample[-1]= 2.0

In [62]:
print(raw_data[0])
print(raw_data[51])
print(raw_data[101])

[5.1, 3.5, 1.4, 0.2, 0.0]
[6.4, 3.2, 4.5, 1.5, 1.0]
[5.8, 2.7, 5.1, 1.9, 2.0]


In [63]:
print(raw_data[-3:])
print(len(raw_data))
raw_data = raw_data[:150]

[[5.9, 3.0, 5.1, 1.8, 2.0], [0.0], [0.0]]
152


In [64]:
print(len(raw_data))

150


In [65]:
np.data = np.array(raw_data)
np.data.shape
np.data[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

### 기본 통계값

* 전체(150샘플)평균, 표준편차 - sepal, length, sepal width, patal length, petal width

* 품종별(50개씩) 평균, 표준편차

* 평균 np.mean()

* 표준편차 np.std()


In [83]:
#print(np.data[:3]) 
print(np.mean(np.data, axis=0))
print(np.std(np.data, axis=0))
print(np.corrcoef(np.data.T)) #상관도 / 품종하고 상관도가 높은것 


[5.84333333 3.054      3.75866667 1.19866667 1.        ]
[0.82530129 0.43214658 1.75852918 0.76061262 0.81649658]
[[ 1.         -0.10936925  0.87175416  0.81795363  0.78256123]
 [-0.10936925  1.         -0.4205161  -0.35654409 -0.4194462 ]
 [ 0.87175416 -0.4205161   1.          0.9627571   0.94904254]
 [ 0.81795363 -0.35654409  0.9627571   1.          0.95646382]
 [ 0.78256123 -0.4194462   0.94904254  0.95646382  1.        ]]


In [86]:
filter_setosa = np.data[:, -1]==0.0
filter_versicolor = np.data[:, -1] == 1.0
filter_virginica = np.data[:, -1]==2.0

print(np.mean(np.data[filter_setosa], axis=0))
print(np.std(np.data[filter_setosa], axis=0))

print(np.mean(np.data[filter_versicolor],axis=0))
print(np.std(np.data[filter_versicolor], axis=0))

[nan nan nan nan nan]
[nan nan nan nan nan]
[5.84333333 3.054      3.75866667 1.19866667 1.        ]
[0.82530129 0.43214658 1.75852918 0.76061262 0.        ]


c:\Users\ITPS\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\ITPS\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:184: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
c:\Users\ITPS\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
c:\Users\ITPS\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:226: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
c:\Users\ITPS\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:258: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
