In [5]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(100, 110)
print(a1, a2)
print(a1+a2)
a3 = np.array([5]*10) #5로 가득차있는 값
print(a3)
print(a1 + a3)
print(a1+5)
#브로드케스팅 
#a1+ a3과 a1+5의 결과는 같다
#전파시킨다는 의미와 비슷하다

[0 1 2 3 4 5 6 7 8 9] [100 101 102 103 104 105 106 107 108 109]
[100 102 104 106 108 110 112 114 116 118]
[5 5 5 5 5 5 5 5 5 5]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14]


In [8]:
# f(x) = 3x + 5
#x=0에서 100사이 짝수일때 f(x)의 합

x=np.arange(0, 101, 2)
print(x) 
print(sum(3*x+5)) #균일하게 3을 곱해준 결과에다 균일하게 5를 더해준 값의 합 

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
7905


In [17]:
a2  = np.arange(30).reshape(5,6) #2차원배열
print(a2) 
a3 = np.arange(6)
print(a3)
a4 = np.arange(100, 130).reshape(5,6)
print(a4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[0 1 2 3 4 5]
[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]


In [19]:
#print(a2+ 100) #1차원 배열과 그냥 숫자(하나의 값을 더해줌 )
print(a2+a3)
#브로드케스트는 2개가 같이 될수없음 브로드케스트를 할때는 shape의 조합을 봐야한다
#a2 :(5,6)
#a3: (6,)
#a4 : (5,6)
#브로드케스트는 내부에서부터 봐야함 a2의 일차원의 모양은 6개가 있음 , 6개를 맞춰야만 브로드케스트가 가능함 
#오른쪽부터 갯수가 맞아야함 (shape)



[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]
 [24 26 28 30 32 34]]


In [21]:
a10 = np.arange(3*5*7*8).reshape(3,5,7,8)
print(a10.shape)
#스칼라
#(8, )
#(7,8)
#(5,7,8)
#(3,5,7,8)

(3, 5, 7, 8)


In [27]:
a15  =np.arange(15).reshape(5,3)
print(a15, a15.shape)
#axis1의 3개의 값 중 
#- 첫번째는 곱하기 2
#- 두번째는 곱하기 10
#-  세번째는 곱하기 12
#axis0을 따라 합계 구하기

x = np.array([2, 10, 12])
print(x, x.shape)
x1 = a15*x
#print(x1)
print(np.sum(x1, axis=1))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] (5, 3)
[ 2 10 12] (3,)
[ 34 106 178 250 322]
