In [2]:
#python List
lista = []
print(lista)

lista.append('a')
print(lista)

[]
['a']


In [10]:
#numpy ndarray
import numpy as np

array1 = np.array(lista)
array2 = np.array([1,2,3,4])
array3 = np.array([x for x in range(5)])

print(array1, type(array1))
print(array3)
#array1.append('c')
#print(array1)
print(array3[[1,4]])
print(array3[array3%2==0])
print(array3[array3>2])

['a'] <class 'numpy.ndarray'>
[0 1 2 3 4]
[1 4]
[0 2 4]
[3 4]


In [14]:
# for , if
#for i in array3:
#    print(i)

for i in range(5):   #np.arrange(5)
    if i>2:
        print(i)

3
4


In [20]:
#function

def function_name(n):
   return n*10

return_value = function_name(20)
print('return_value:', return_value)

assert function_name(100) ==1000

return_value: 200


In [36]:
import random

random.seed(123)
listb = []
for i in range(10):
    listb.append(random.randint(0, 100))
    print(listb)

listc = [ random.randint(0, 100) for _ in range(10)]
print(listc) 

#listb에서 50보다 큰 것을 출력

listb_np = np.array(listb)
print(listb_np[listb_np>50])

#50보다 큰것의 갯수
print(len(listb_np[listb_np>50]))


[6]
[6, 34]
[6, 34, 11]
[6, 34, 11, 98]
[6, 34, 11, 98, 52]
[6, 34, 11, 98, 52, 34]
[6, 34, 11, 98, 52, 34, 13]
[6, 34, 11, 98, 52, 34, 13, 4]
[6, 34, 11, 98, 52, 34, 13, 4, 48]
[6, 34, 11, 98, 52, 34, 13, 4, 48, 68]
[71, 42, 43, 6, 20, 17, 43, 71, 42, 89]
[98 52 68]
3
